version: '3.8'

services:
  web:
    image: uas-web-website:latest
    build: .
    container_name: cat-adoption
    ports:
      - "80:80"
    restart: always

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: monitoring_cat_adoption
    ports:
      - "8888:3001"
    volumes:
      - uptime-kuma-cat-data:/app/data
    restart: always

volumes:
  uptime-kuma-cat-data:
