name: Deploy UAS Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/cantikrahmi/UAS
          git pull origin main
          docker compose down
          docker compose up -d --build
